name: snap-hello # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple helloworld app in snap package # 79 char long summary
description: |
  Example of packaging a simple "helloworld" application into a SNAP package
  Пример упаковки простого приложения "helloworld" в пакет SNAP

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snap-hello:
    # See 'snapcraft plugins'
    plugin: dump
    source: src

apps:
  snap-hello:
    command: snap-hello.sh
  sh:
    command: snap-hello.sh.sh